Repository KratosMultiphysics/KratosSalomePlugin, pull requests merged in 2020-03, with the labels that each got.

#35 Missing elif
  standalone_tui_usage/create_kratos_input.py
Labels: bug

#37 adding initial version of documentation
  README.md
  development/README.md
  documentation/README.md
  documentation/developers_guide.md
  documentation/install_salome.md
  documentation/standalone_usage.md
  plugin/applications/Generic/README.md
  plugin/applications/StructuralMechanics/README.md
Labels: documentation

#38 adding init version of CODEWONERS
  .github/CODEOWNERS
Labels: enhancement

#41 Improve folder structure
  .github/assert_run_in_salome.py
  .github/workflows/ci.yml
  .github/workflows/dockerimage.yml
  .gitignore
  README.md
  create_kratos_input_tui.py
  documentation/developers_guide.md
  execute_in_salome.py
  ks_plugin/__init__.py
  ks_plugin/applications/Generic/README.md
  ks_plugin/applications/Generic/__init__.py
  ks_plugin/applications/Generic/application.py
  ks_plugin/applications/Generic/examples/.gitkeep
  ks_plugin/applications/Generic/ui_forms/.gitkeep
  ks_plugin/applications/StructuralMechanics/README.md
  ks_plugin/applications/StructuralMechanics/__init__.py
  ks_plugin/applications/StructuralMechanics/application.py
  ks_plugin/applications/StructuralMechanics/examples/.gitkeep
  ks_plugin/applications/StructuralMechanics/ui_forms/.gitkeep
  ks_plugin/applications/__init__.py
  ks_plugin/base_application.py
  ks_plugin/geometries_io.py
  ks_plugin/gui/.gitkeep
  ks_plugin/mesh_interface.py
  ks_plugin/model_part.py
  ks_plugin/module_reload_order.py
  ks_plugin/plugin_logging.py
  ks_plugin/ui_forms/.gitkeep
  ks_plugin/utilities/__init__.py
  ks_plugin/utilities/kratos_logo.png
  ks_plugin/utilities/load_plugin.png
  ks_plugin/utilities/salome_utilities.py
  ks_plugin/utilities/utils.py
  ks_plugin/version.py
  ks_plugin/write_mdpa.py
  salome_plugins.py
  tests/test_geometries_io.py
  tests/test_mesh_interface.py
  tests/test_model_part.py
  tests/test_salome_utilities.py
  tests/test_utils.py
  tests/test_write_mdpa.py
  tests/testing_utilities.py
  tui_examples/README.md
  tui_examples/balls_barrier/.gitkeep
  tui_examples/cantilever/MainKratos.py
  tui_examples/cantilever/ProjectParameters.json
  tui_examples/cantilever/README.md
  tui_examples/cantilever/StructuralMaterials.json
  tui_examples/cantilever/pictures/mesh_hexa.png
  tui_examples/cantilever/pictures/mesh_tetra.png
  tui_examples/cantilever/salome_cantilever_hexa.py
  tui_examples/cantilever/salome_cantilever_tetra.py
  tui_examples/flow_cross_chimera/.gitkeep
  tui_examples/flow_cylinder/.gitkeep
  tui_examples/mok_fsi/.gitkeep
  tui_examples/rock_cablenet/.gitkeep
  tui_examples/tower/salome_tower.py
  tui_examples/wind_turbine_blade/.gitkeep
Labels: cleanup

#42 adding canceling of redundant builds
  .github/workflows/ci.yml
Labels: CI
